### ISSUE TITLE
[Request] No sudo

### ISSUE THREAD

**Issue by alexisquintero** [pedorich-n/nixos-mutable-files-manager#1]
Would it be possible to make it run with no sudo and have access to a subset of the fucntionality in that mode? only creating files for/as the current user?

**Comment by pedorich-n** [comment]
Technically it can probably be done using `systemd.user.services`. 
Practically I see few benefits to this. It is possible to set the owner for a file already.

Running the entire unit from a non-root user will only reduce the scope of possible changes (which is safer), and newly created folders will be owned by this user.
